# Travis CI 설정

language: java
jdk:
  - openjdk8

# Travis CI를 어느 브랜치가 푸시될 때 수행할지 지정
# 현재 옵션은 오직 master 브랜치에 push될 때만 수행
branches:
  only:
    - tarvisci_env

# Travis CI 서버의 home
# 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은
# 다음 배포 때 부터 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시 되었을 때 수행하는 명령어
# 여기서는 프로젝트 내부에 둔 gradlew을 통해 clean & build 수행
script: "./gradlew clean build"

# deploy 명령어가 실행되기 전에 수행
# 배포에 필요한 파일은 Jar, appsepc.yml, deploy.sh(배포스크립ㄹ트)이기 때문에 해당 파일들만 포함하도록 설정
# Travis Ci는 S3로 특정 파일만 업로드가 안되고, 디렉토리 단위로만 업로드가 되기 때문에 deploy 디렉ㅌ오리는 항상 생성.
# before_deploy에는 zip 파일에 포함시킬 파일들을 저장
# zip -r 명령어를 통해 before_deploy 디렉토리 전체 파일 압축
#before_deploy:
#  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
#  - cp script/*.sh before-deploy/
#  - cp appspec.yml before-deploy/
#  - cp build/libs/*.jar before-deploy/
#  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동 후 전체 압축
#  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동 후 deploy 디렉토리 생성
#  - mv before-deploy/before-deploy.zip deploy/monkey-music.zip # deploy로 zip파일 이동
#
## s3로 파일업로드 혹은 codeDeploy로 배포 등 외부 서비스와 연동될 행위들 선언
#deploy:
#  - provider: s3
#    # Travis repo settings에 설정된 값
#    access_key_id: $AWS_ACCESS_KEY
#    # Travis repo setting에 설정된 값
#    secret_access_key: $AWS_SECRET_KEY
#    # s3 버킷
#    bucket: monkey-music-build
#    region: ap-northeast-2
#    skip_cleanup: true
#    # zip 파일 접근을 private으로 설정
#    acl: private
#    # 앞에서 생성한 deploy 디렉토리를 지정
#    # 해당 위치의 파일든만 s3 전송 가능
#    local_dir: deploy
#    wait-until-deployed: true
#
#  - provider: codedeploy
#    # Travis repo settings에 설정된 값
#    access_key_id: $AWS_ACCESS_KEY
#    # Travis repo setting에 설정된 값
#    secret_access_key: $AWS_SECRET_KEY
#    # S3 버킷
#    bucket: monkey-music-build
#    # 빌드 파일을 압축해서 전달달
#    key: monkey-music.zip
#    # 압축 확장자
#    bundle_type: zip
#    # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
#    application: monkey-music
#    # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
#    deployment_group: monkey-music-group
#    region: ap-northeast-2
#    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - lbd4946@gmail.com